# Default values for holmes-mock
replicaCount: 1

image:
  repository: node
  pullPolicy: IfNotPresent
  tag: "24-alpine"

service:
  type: ClusterIP
  port: 5050

resources:
  limits:
    cpu: 100m
    memory: 128Mi
  requests:
    cpu: 50m
    memory: 64Mi
