version: "3.8"

configs:
  e2e_config:
    external: true
    name: kdb_e2e_config

secrets:
  e2e_secret:
    external: true
    name: kdb_e2e_secret

networks:
  e2e_net:
    external: true
    name: kdb_e2e_net

volumes:
  e2e_data:

services:
  a-replicated:
    image: nginx:alpine
    networks:
      - e2e_net
    deploy:
      replicas: 1
      restart_policy:
        condition: any

  b-logger:
    image: alpine:3.19
    command: ['sh', '-c', 'while true; do echo "kdb-e2e log"; sleep 2; done']
    networks:
      - e2e_net
    volumes:
      - e2e_data:/data
    configs:
      - source: e2e_config
        target: /etc/kdb/config.txt
    secrets:
      - source: e2e_secret
        target: kdb_secret.txt
    deploy:
      replicas: 1
      restart_policy:
        condition: any
