// Thin service layer wrapping Wails-generated backend functions.
// This creates a single import surface so future concerns (logging, retry, normalization)
// can be added without touching many UI files.

import {
  GetConfigMaps,
  GetCronJobs,
  GetCurrentConfig,
  GetDaemonSets,
  GetDeployments,
  GetIngresses,
  GetJobs,
  GetKubeContexts,
  GetNamespaces,
  GetOverview,
  GetPersistentVolumeClaims,
  GetPersistentVolumes,
  GetPodStatusCounts,
  GetReplicaSets,
  GetRunningPods,
  GetSecrets,
  GetStatefulSets,
  SetCurrentKubeContext,
  SetCurrentNamespace,
  GetConnectionStatus,
  GetResourceCounts,
  SetPreferredNamespaces,
  StartJob,
  SuspendCronJob,
  ResumeCronJob,
  StartJobFromCronJob,
} from '../../../wailsjs/go/main/App';

// Direct re-exports for now. Wrapper functions retained for possible future enhancements.
export {
  GetConfigMaps,
  GetCronJobs,
  GetCurrentConfig,
  GetDaemonSets,
  GetDeployments,
  GetIngresses,
  GetJobs,
  GetKubeContexts,
  GetNamespaces,
  GetOverview,
  GetPersistentVolumeClaims,
  GetPersistentVolumes,
  GetPodStatusCounts,
  GetReplicaSets,
  GetRunningPods,
  GetSecrets,
  GetStatefulSets,
  SetCurrentKubeContext,
  SetCurrentNamespace,
  GetConnectionStatus,
  GetResourceCounts,
  SetPreferredNamespaces,
  StartJob,
  SuspendCronJob,
  ResumeCronJob,
  StartJobFromCronJob,
};
