// Thin service layer wrapping Wails-generated backend functions.
// This creates a single import surface so future concerns (logging, retry, normalization)
// can be added without touching many UI files.

import {
  CreateResource,
  GetKubeConfigs,
  GetConfigMaps,
  GetCronJobs,
  GetCurrentConfig,
  GetDaemonSets,
  GetDeployments,
  GetIngresses,
  GetJobs,
  GetHorizontalPodAutoscalers,
  GetHorizontalPodAutoscalerDetail,
  GetKubeContexts,
  GetNamespaces,
  GetNodes,
  GetOverview,
  GetPodsOnNode,
  GetPersistentVolumeClaims,
  GetPersistentVolumes,
  GetPodStatusCounts,
  GetReplicaSets,
  GetRunningPods,
  GetSecrets,
  GetStatefulSets,
  SetCurrentKubeContext,
  SetCurrentNamespace,
  GetConnectionStatus,
  GetResourceCounts,
  SetPreferredNamespaces,
  StartJob,
  SuspendCronJob,
  ResumeCronJob,
  StartJobFromCronJob,
  ScaleResource,
  ResizePersistentVolumeClaim,
  // Proxy configuration
  GetProxyConfig,
  SetProxyConfig,
  ClearProxyConfig,
  DetectSystemProxy,
  // Enterprise auth (Gaps 2-7)
  ConnectInsecure,
  RefreshCredentials,
  GetKubeconfigPaths,
  SetKubeconfigPaths,
  DetectKubeconfigEnvPaths,
  SetSessionProbeInterval,
  GetSessionProbeInterval,
} from '../../../wailsjs/go/main/App';

// Direct re-exports for now. Wrapper functions retained for possible future enhancements.
export {
  CreateResource,
  GetKubeConfigs,
  GetConfigMaps,
  GetCronJobs,
  GetCurrentConfig,
  GetDaemonSets,
  GetDeployments,
  GetIngresses,
  GetJobs,
  GetHorizontalPodAutoscalers,
  GetHorizontalPodAutoscalerDetail,
  GetKubeContexts,
  GetNamespaces,
  GetNodes,
  GetOverview,
  GetPodsOnNode,
  GetPersistentVolumeClaims,
  GetPersistentVolumes,
  GetPodStatusCounts,
  GetReplicaSets,
  GetRunningPods,
  GetSecrets,
  GetStatefulSets,
  SetCurrentKubeContext,
  SetCurrentNamespace,
  GetConnectionStatus,
  GetResourceCounts,
  SetPreferredNamespaces,
  StartJob,
  SuspendCronJob,
  ResumeCronJob,
  StartJobFromCronJob,
  ScaleResource,
  ResizePersistentVolumeClaim,
  // Proxy configuration
  GetProxyConfig,
  SetProxyConfig,
  ClearProxyConfig,
  DetectSystemProxy,
  // Enterprise auth (Gaps 2-7)
  ConnectInsecure,
  RefreshCredentials,
  GetKubeconfigPaths,
  SetKubeconfigPaths,
  DetectKubeconfigEnvPaths,
  SetSessionProbeInterval,
  GetSessionProbeInterval,
};
