severity:
  - CRITICAL
  - HIGH
  - MEDIUM

vulnerability:
  type:
    - os
    - library

scan:
  scanners:
    - vuln
    - secret
    - misconfig

format: json

exit-code: 0  # Don't fail, just report
